import { contextBridge, ipcRenderer } from 'electron';
const allowedChannels = new Set([
  "backup:create", "backup:restore", "backup:pending-storage", "backup:ack-storage", "backup:restart",
  "ai-analyst:analyze",
  "app:get-config",
  "app:get-status",
  "app:collector-health",
  "app:is-admin",
  "app:save-config",
  "app:toggle-module",
  "assets:get-all",
  "assets:interfaces",
  "assets:query",
  "assets:scan",
  "behavior:summary",
  "certs:list",
  "certs:summary",
  "connection:active",
  "connectivity:connect",
  "connectivity:disconnect",
  "connectivity:get-state",
  "connectivity:test",
  "correlation:clear-history",
  "correlation:get-history",
  "correlation:investigate-indicator",
  "correlation:investigate-ip",
  "dashboard:metrics",
  "dashboard:stats",
  "dfir:add-evidence",
  "dfir:acquire-evidence",
  "dfir:verify-evidence",
  "dfir:analyze-artifact",
  "dfir:analysis-history",
  "dfir:get-artifacts",
  "dfir:get-chain-of-custody",
  "dfir:get-evidence",
  "dfir:get-memory-analysis",
  "dfir:get-registry-keys",
  "dlls:list",
  "dlls:summary",
  "dns:analyze",
  "dns:domain-detail",
  "dns:query",
  "dns:summary",
  "dns:sync",
  "events:bookmark",
  "events:query",
  "events:health",
  "events:sync",
  "fim:baseline",
  "fim:changes",
  "fim:scan",
  "fim:summary",
  "fim:watch-paths",
  "internet:clear-cache",
  "internet:get-configs",
  "internet:get-global-config",
  "internet:get-health",
  "internet:query",
  "internet:remove-api-key",
  "internet:save-config",
  "internet:save-global-config",
  "internet:test-connections",
  "ioc:scan",
  "ioc:evaluate-rule",
  "ioc:rule-list", "ioc:rule-save",
  "module-manager:activate",
  "module-manager:get-status",
  "perf:export-diagnostics",
  "perf:get-metrics",
  "persistence:registry",
  "persistence:services",
  "persistence:startup",
  "persistence:summary",
  "persistence:tasks",
  "plugins:rescan",
  "plugins:summary",
  "process:list",
  "process:modules",
  "process:terminate",
  "process:threads",
  "rdp:events",
  "rdp:sessions",
  "rdp:summary",
  "redteam:analyze-http",
  "redteam:check-nmap",
  "redteam:get-attack-surface",
  "redteam:get-dns-intelligence",
  "redteam:inspect-ssl",
  "redteam:scan-ports",
  "reports:generate",
  "reputation:host-detail",
  "reputation:list",
  "reputation:recalculate",
  "reputation:summary",
  "smb:sessions",
  "smb:shares",
  "smb:summary",
  "threads:list",
  "threads:summary",
  "timeline:bookmark",
  "timeline:query",
  "timeline:stats",
  "usb:devices",
  "usb:scan",
  "usb:summary"
]);
const allowedEvents = new Set<string>([]);
contextBridge.exposeInMainWorld('lsip', {
  invoke: async (channel: string, ...args: any[]) => {
    if (!allowedChannels.has(channel)) throw new Error('Unauthorized IPC channel');
    return ipcRenderer.invoke(channel, ...args);
  },
  on: (channel: string, callback: (...args: any[]) => void) => {
    if (!allowedEvents.has(channel)) return () => {};
    const subscription = (_event: any, ...args: any[]) => callback(...args);
    ipcRenderer.on(channel, subscription);
    return () => ipcRenderer.removeListener(channel, subscription);
  },
  send: (_channel: string, ..._args: any[]) => { /* No fire-and-forget actions are exposed. */ }
});
